config/routes.rb
Airmelive::Application.routes.draw do

  root :to => 'users#index'

  get "index" => "users#index"
  post "new" => "users#new"
  get "public_profile/:id" => "users#public_profile", as: "public_profile"
  get "/login_details/:id" => "sessions#login_details", as: "login_details"
  patch "login_details/:id" => "sessions#update" , as: "update"
  get "profile/:id" => "sessions#profile", as: "profile"
  get "log_out" => "sessions#log_out"
  get "profile/:id/edit" => "sessions#edit", as:"edit"

  resources :sessions do
  end

  get '/admin', to: 'admins#index'
  get  '/admins/show', to: 'admins#show', as: 'show'
  post  '/admins/show/:id/delete', to: 'admins#delete', as: 'delete_event'
  post '/admins/:id/edit', to: 'admins#edit_event', as: 'edit_event'
  get '/admins/hangout_xml' , to: 'admins#hangout_xml'
  get 'admin/register_hangout',  to: 'admins#save_json_data'
  get 'admins/show/audition/:id', to: 'admins#audition', as: 'audition'
  resources :users
  resources :events
  resources :admins

  get '/upcomingevents', to: 'events#upcoming_events'
  post '/upcomingevents/:id', to: 'events#post_upcoming_events', as: "upcoming"
  get '/upcomingevents/:id/show', to: 'events#show_up', as: "upcoming_each"
  get '/ongoingevents', to: 'events#ongoing_events'
  get '/auditionevents', to: 'events#audition_events'
  get '/home', to: 'events#home'

end

app/views/admins/audition.html.erb
<div class="container">

<h4 align="center"><%= @event.eventname.upcase %></h4>
<div class="row">
    <%= image_tag @event.cloud_url ,:class => 'image_show_up' %>
</div>

<br><legend>Participants</legend><br>

<% if @users %>
  <% @users.each do |t| %>
    <div class="row">
      <div class="col-md-6">
        <%= t.name %>
      </div>
      <div class="col-md-6">
        <form action= "https://talkgadget.google.com/hangouts/_" method = "GET">
        <input type = "hidden" name = "gid" value = "1009023439918">
        <input type = "hidden" name = "hso" value = "0">
        <select name= "gd">
        <option><%= t.id %></option>
        </select>
        <input type="submit" value="Hangout"/>
        </form>
      </div>
    </div><br>
  <% end %>
<% else %>
    <h1> No Participants</h1>
<% end %>



<script src="//hagoutsapi.talkgadget.google.com/talkgadget/apps/gadgets/js/rpc.js"></script>
<script src="//hagoutsapi.talkgadget.google.com/hangouts/api/hangout.js?v=1.0"></script>
<script src="//www.google.com/jsapi"></script>
<script type="text/javascript">google.load("jquery", "1.7.1");</script>

========================================================

app/views/admins/edit_event.html.erb
    <div class ="container">
    <div class="row">

      <div class="col-md-2"></div>

      <div class="col-md-8" style = "border:solid ">
        
          <h1 style = "color:green">Edit Event</h1><br>
          <%= form_for @event_edit,:html => {:multipart => true},:url => {:controller => "admins", :action => "update"} do |f| %>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventname %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventname%>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :category %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :category%>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :registrationopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :registrationopen, :id => 'datetimepicker1'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :registrationclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :registrationclose, :id => 'datetimepicker2'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :auditionopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :auditionopen, :id => 'datetimepicker3'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :auditionclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :auditionclose, :id => 'datetimepicker4'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventopen, :id => 'datetimepicker5'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventclose, :id => 'datetimepicker6'  %>
                </div>    
            </div>
            <br>
             <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :rules %>:
                </div>
                <div class="col-md-4">
                   <%= f.text_area :rules%>
                </div>    
            </div>
            <br>              
            <%= f.file_field :avatar %><br>
            <%= button_tag 'Reset', :type => 'reset' %>
            <%= f.submit "Edit" %>
          <% end %>
        <br>
      </div>

      <div class="col-md-2"></div>

    </div>
</div> 
<br><br><br> 

<legend></legend>  
<script>
$( document ).ready(function() {  
    $('#datetimepicker1').datetimepicker();
    $('#datetimepicker2').datetimepicker();
    $('#datetimepicker3').datetimepicker();
    $('#datetimepicker4').datetimepicker();
    $('#datetimepicker5').datetimepicker();
    $('#datetimepicker6').datetimepicker();
});
</script>

app/views/admins/index.html.erb
<div class ="container">
    <div class="row">

      <div class="col-md-2"><%= link_to  "Events" , show_path %> </div>

      <div class="col-md-8" style = "border:solid ">
        
          <legend><h1 style = "color:green">Create Event</h1></legend><br>
         <%= form_for @event,:html => { :multipart => true }, :url => {:controller => "admins", :action => "create"} do |f| %>
            <%= flash[:notice] %>
            <%= @file.public_url if @file%>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventname %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventname%>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :category %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :category%>
                </div>    
            </div>
            <br>
             <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :registrationopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :registrationopen, :id => 'datetimepicker1'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :registrationclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :registrationclose, :id => 'datetimepicker2'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :auditionopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :auditionopen, :id => 'datetimepicker3'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :auditionclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :auditionclose, :id => 'datetimepicker4'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventopen %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventopen, :id => 'datetimepicker5'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :eventclose %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_field :eventclose, :id => 'datetimepicker6'  %>
                </div>    
            </div>
            <br>
            <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :description %>:
                </div>
                <div class="col-md-4">
                    <%= f.text_area :description%>
                </div>    
            </div>
            <br>
             <div class = "row">                  
                <div class="col-md-3">
                    <%= f.label :rules %>:
                </div>
                <div class="col-md-4">
                   <%= f.text_area :rules%>
                </div>    
            </div>
            <br>              
            <%= f.file_field :avatar %><br>
            <%= button_tag 'Reset', :type => 'reset' %>
            <%= f.submit "Create" %>
          <% end %>
        <br>
      </div>

      <div class="col-md-2"></div>

    </div>
</div> 
<br><br><br>
<script>
$( document ).ready(function() {
    $('#datetimepicker1').datetimepicker();
    $('#datetimepicker2').datetimepicker();
    $('#datetimepicker3').datetimepicker();
    $('#datetimepicker4').datetimepicker();
    $('#datetimepicker5').datetimepicker();
    $('#datetimepicker6').datetimepicker();
});
</script>
<legend><br><br></legend>  

app/views/admins/show.html.erb
<div class = "container">
  <% if @upcoming_events.empty? %> 

  	<h1 align="center"> No Upcoming Events!!! </h1>

  <% else %> 

    <h3 style="color:green">Upcoming Events</h3>
    <div class="row">
      
    <% @upcoming_events.each do |t| %>
      
      <div class="col-md-4">
        <div class="thumbnail">
        	<p><%=  t.eventname.upcase %> </p>
          <%= image_tag t.cloud_url ,:class => 'image_show' %>
          <div class="caption">
            <p><%= t.description %></p>               
	            <div class ="row">
	             		<div class= "col-md-1">  </div>
	             		<div class = "col-md-2">
				            <%= button_to "Edit",  edit_admin_path(t), class: "btn btn-success" %>
				          </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  	
		             		<%= button_to "Delete", delete_event_path(t),:confirm => "Do you want to delete this event?",class: "btn btn-danger" %>
		             	</div>	
	            </div>           
          </div>
        </div>
      </div>

    <% end %>
    </div>
    <% end %>
    <legend><br></legend><br>

  <% if @ongoing_events.empty? %> 

  	<h1 align="center"> No Ongoing Events!!! </h1>

  <% else %> 

    <h3 style="color:green">Ongoing Events</h3>
    <div class="row">
      
    <% @ongoing_events.each do |t| %>
      
      <div class="col-md-4">
        <div class="thumbnail">
          <p><%=  t.eventname.upcase %> </p>
          <%= image_tag t.cloud_url ,:class => 'image_show' %>
         	<div class="caption">
            <p><%= t.description %></p>               
            	<div class ="row">
	             		<div class= "col-md-1">  </div>
	             		<div class = "col-md-2">
				            <%= button_to "Edit",  edit_admin_path(t), class: "btn btn-success" %>
				          </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  	
		             		<%= button_to "Delete", delete_event_path(t),:confirm => "Do you want to delete this event?", class: "btn btn-danger" %>
		             	</div>	
	            </div>                      
          </div>
        </div>
      </div>

    <% end %>
    </div>
    <% end %>  
    <legend><br></legend><br>

    <% if @auditioning_events.empty? %> 

    <h1 align="center"> No Auditioning Events!!! </h1>

  <% else %> 

    <h3 style="color:green">Auditioning Events</h3>
    <div class="row">
      
    <% @auditioning_events.each do |t| %>
      
      <div class="col-md-4">
        <div class="thumbnail">
          <p><%= link_to t.eventname.upcase , audition_path(t),:style => 'text-decoration: none'  %> </p>
          <%= image_tag t.cloud_url ,:class => 'image_show' %>
          <div class="caption">
            <p><%= t.description %></p>               
              <div class ="row">
                  <div class= "col-md-1">  </div>
                  <div class = "col-md-2">
                    <%= button_to "Edit",  edit_admin_path(t), class: "btn btn-success" %>
                  </div>
                  <div class= "col-md-2">  </div>
                  <div class= "col-md-2">  </div>
                  <div class= "col-md-2">   
                    <%= button_to "Delete", delete_event_path(t),:confirm => "Do you want to delete this event?", class: "btn btn-danger" %>
                  </div>  
              </div>                      
          </div>
        </div>
      </div>

    <% end %>
    </div>
    <% end %>  

    <legend><br></legend><br>

  <% if @event_list.empty? %> 

  	<h1 align="center"> No Events!!! </h1>

  <% else %> 

    <h3 style="color:green">All Events</h3>
    <div class="row">      
	    <% @event_list.each do |t| %>	      
	      <div class="col-md-4">
	        <div class="thumbnail">
	        	<p><%=  t.eventname.upcase %> </p>
	          <%= image_tag t.cloud_url ,:class => 'image_show' %>
	          <div class="caption">
	            <p><%= t.description %></p>               
	             	<div class ="row">
	             		<div class= "col-md-1">  </div>
	             		<div class = "col-md-2">
				            <%= button_to "Edit",  edit_admin_path(t), class: "btn btn-success" %>
				          </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  </div>
				          <div class= "col-md-2">  	
		             		<%= button_to "Delete", delete_event_path(t),:confirm => "Do you want to delete this event?", class: "btn btn-danger" %>
		             	</div>	
	            	</div>                  
	          </div>
	        </div>
	      </div>

	    <% end %>
    </div>
  <% end %>   
</div>
<legend><br></legend><br>