config/routes.rb
Airmelive::Application.routes.draw do

  root :to => 'users#index'

  get "index" => "users#index"
  post "new" => "users#new"
  get "public_profile/:id" => "users#public_profile", as: "public_profile"
  get "/login_details/:id" => "sessions#login_details", as: "login_details"
  patch "login_details/:id" => "sessions#update" , as: "update"
  get "profile/:id" => "sessions#profile", as: "profile"
  get "log_out" => "sessions#log_out"
  get "profile/:id/edit" => "sessions#edit", as:"edit"

  resources :sessions do
  end

  get '/admin', to: 'admins#index'
  get  '/admins/show', to: 'admins#show', as: 'show'
  post  '/admins/show/:id/delete', to: 'admins#delete', as: 'delete_event'
  post '/admins/:id/edit', to: 'admins#edit_event', as: 'edit_event'
  get '/admins/hangout_xml' , to: 'admins#hangout_xml'
  get 'admin/register_hangout',  to: 'admins#save_json_data'
  get 'admins/show/audition/:id', to: 'admins#audition', as: 'audition'
  resources :users
  resources :events
  resources :admins

  get '/upcomingevents', to: 'events#upcoming_events'
  post '/upcomingevents/:id', to: 'events#post_upcoming_events', as: "upcoming"
  get '/upcomingevents/:id/show', to: 'events#show_up', as: "upcoming_each"
  get '/ongoingevents', to: 'events#ongoing_events'
  get '/auditionevents', to: 'events#audition_events'
  get '/home', to: 'events#home'

end

app/models/user.rb
class User < ActiveRecord::Base
	include ImageUpload
	has_many :user_events
	has_many :events, :through => :user_events
	validates :name, :presence => true
	validates :gplus, :uniqueness => true, :presence => true
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/default_profile.jpg"

=begin 
  User details validation.
=end
	def user_details
		if avatar and likes and dislikes and ambition and talent and aboutme != "" or nil
			true
		else
			false
		end	
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_action :require_login

=begin 
  redirects to the index page of the application.
=end  

	def index
	end

=begin 
  creates a new user if not registered before.
  if a Google account already exists, then log in with existing account username and password.
=end

	def new
  	user = User.find_by_gplus(params[:gplus])
    if user
    	redirect_to login_details_path(user), notice: "You are already registered!"
  	else
    	@fullname = params[:fullname]
    	@gplusId = params[:gplus]
    	u = User.new(:name => params[:fullname], :gplus => params[:gplus], :email=> params[:email])
    	if u.save
    	 redirect_to login_details_path(u), notice: "User with name #{@fullname} and Google+ ID #{@gplusId} has been successfully registered!"
      else
        render "index"
  	  end
	  end
  end

=begin 
  Profile page of a user visible to all.
=end

  def public_profile
    @user = User.find params[:id]
  end

  private

=begin 
  Strong parameters of User.
=end
    def user_params
      params.require(:user).permit(:name, :gplus, :avatar, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<style>
  #main_contain{
    background-image:url('http://ppcdn.500px.org/55334198/cca1354f36c6c3c3e4fdba64a2b55f063812d9d2/2048.jpg');
    background-size: cover;
    background-repeat: no-repeat;
    width:auto;
      }
      h5{
        color:white;
      }
</style>
<div id="main_contain">
  <header id="header" class="header"  data-offset-top="20" style="background-color:#0B243B" >
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1><span style="color:white">AIRME</span><span style="color:green">LIVE</span></h1>
      </div>
      <div class="col-md-6">
        <%= link_to "Explore", home_path, :class =>  "btn btn-success btn-sm", :style => "float:right"%>
      </div>
    </div>
  </div>
</header>
  


  <div class="row"  style="margin-top:500px;">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h6 style="color:red;"><%= flash[:error] %></h6>
      <span id="signinButton">
        <span
          class="g-signin"
          data-callback="signinCallback"
          data-clientid="191444374770-fjnace5l9n20phsj5hjdutesmgvri9pt.apps.googleusercontent.com"
          data-clientsecret="dB2xBwxF-BxT_kGKP0nGUpNk"
          data-cookiepolicy="single_host_origin"
          data-scope="https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email">
        </span>
      </span>
  

      

      <%= form_tag(:controller => "users", :action => "new", :method => "post") do %>
        <div class="is-this-you"></div>
        <%= hidden_field_tag :fullname %>
        <%= hidden_field_tag :gplus %>
        <%= hidden_field_tag :email %>
      <% end %>
    </div>  

      <script type="text/javascript">
        (function() {
           var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
           po.src = 'https://apis.google.com/js/client:plusone.js';
           var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();

        function signinCallback(authResult) {
          var token = gapi.auth.getToken();
          var accessToken = token.access_token;
          if (authResult['access_token']) {
            var accessUrl = 'https://www.googleapis.com/plus/v1/people/me?access_token=' + accessToken;
            $.ajax({
              type: 'GET',
              url: accessUrl,
              async: false,
              contentType: 'application/json',
              dataType: 'jsonp',
              success: function(data) {
                var originalImage = data.image.url;
                var imageUrl = originalImage.slice(0, -2);
                var gplusImage = imageUrl + "200";
                $('#fullname').val(data.displayName);
                $('#gplus').val(data.id);
                $('#email').val(data.emails[0].value)
                $('.is-this-you').html("<h5>" + data.displayName + "</h5><br><input type='submit' class ='btn btn-mini btn-success' value='Login or Register'>");
              },
              error: function(e) {
                console.log(e);
              }
            });
          } else if (authResult['error']) {
              $('.is-this-you').html("<h4>Your request could not be completed at this time</h4>");
            };
        }
      </script>
    
  </div>
  <br><br><br>
</div>

app/views/users/public_profile.html.erb
<section id="main-and-sidebar" class="pad-25">
    <div class="container offset2">
        <div class="row">
            <div class="col-md-4 main">
                <h2><%= @user.name.upcase %></h2><br>
                <div class="img-thumbnail">
                    <%= image_tag @user.user_cloud_url, :size => "250x250" %>
                </div>
            </div>
            <div class="col-md-4 main">
                <h5><%= @user.name %></h5><br>
                <h5><%= @user.age %></h5><br>
                <h5><%= @user.city %></h5><br>
                <h5><%= @user.country %></h5><br>
                <h5><%= @user.email %></h5><br><br><br><br><br><br><br>
            </div>
        </div>

        <legend class="section"><br></legend>
        
        <div class="row">
            <div class="col-md-12 main">
                <div class="panel panel-primary">
                    <div class="panel-heading"><h5>Likes / Hobbies  </h5></div>
                    <h6><%= @user.likes %></h6>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading"><h5>Dislikes  </h5></div>
                    <h6><%= @user.dislikes %></h6>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading"><h5>Ambition  </h5></div>
                    <h6><%= @user.ambition %></h6>
                </div>
                 <div class="panel panel-primary">
                    <div class="panel-heading"><h5>Talents  </h5></div>
                    <h6><%= @user.talent %></h6>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading"><h5>About me  </h5></div>
                    <h6><%= @user.aboutme %></h6>
                </div>
            </div>
        </div>
        
        <legend class="section"><h3>Participating Events</h3></legend>
        
        
<% unless @user.events.empty? %>
  
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% t = @user.events.sort.first %>
      <div class="item active">
        <a href="/upcomingevents/<%= t.id %>/show"><%= image_tag t.cloud_url ,:class => 'image_slider' %></a>
        <div class="carousel-caption">
          <b style="color:white;"><%= t.eventname %></b>
        </div>
      </div>
      <% user_events = @user.events.sort%>
      <% for i in 1..user_events.count %>
          <% if user_events[i] %>
              <div class="item">
                <a href="/upcomingevents/<%= user_events[i].id %>/show"><%= image_tag user_events[i].cloud_url ,:class => 'image_slider' %></a>
                <div class="carousel-caption">
                 <b style="color:white;"> <%= user_events[i].eventname %></b>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>

<% end %>
        <legend class="section"><br></legend>

    </div>
</section>