config/routes.rb
Airmelive::Application.routes.draw do

  root :to => 'users#index'

  get "index" => "users#index"
  post "new" => "users#new"
  get "public_profile/:id" => "users#public_profile", as: "public_profile"
  get "/login_details/:id" => "sessions#login_details", as: "login_details"
  patch "login_details/:id" => "sessions#update" , as: "update"
  get "profile/:id" => "sessions#profile", as: "profile"
  get "log_out" => "sessions#log_out"
  get "profile/:id/edit" => "sessions#edit", as:"edit"

  resources :sessions do
  end

  get '/admin', to: 'admins#index'
  get  '/admins/show', to: 'admins#show', as: 'show'
  post  '/admins/show/:id/delete', to: 'admins#delete', as: 'delete_event'
  post '/admins/:id/edit', to: 'admins#edit_event', as: 'edit_event'
  get '/admins/hangout_xml' , to: 'admins#hangout_xml'
  get 'admin/register_hangout',  to: 'admins#save_json_data'
  get 'admins/show/audition/:id', to: 'admins#audition', as: 'audition'
  resources :users
  resources :events
  resources :admins

  get '/upcomingevents', to: 'events#upcoming_events'
  post '/upcomingevents/:id', to: 'events#post_upcoming_events', as: "upcoming"
  get '/upcomingevents/:id/show', to: 'events#show_up', as: "upcoming_each"
  get '/ongoingevents', to: 'events#ongoing_events'
  get '/auditionevents', to: 'events#audition_events'
  get '/home', to: 'events#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
	include ImageUpload
	has_many :user_events
	has_many :users, :through => :user_events
	
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates :eventname, :presence => {:message => "can't be empty"},:uniqueness => true, :length => { :in => 2..20 }
	validates :category, :presence => true
	validates :description, :presence => true
	validates :rules, :presence => true

=begin 
  Auto Publish into Facebook.
=end

	def facebook_post
		owner = FbGraph::User.me("CAADLVlmd6d4BAJ8EZBrZC9lcxQvf945umxZCIocJuHXTMO3HZB37WPdogBeWhoeUBnqE8297z32f6Dbkx3DakntN6qdTMP96Uqob67WkdKRkxF6RN7CQiYvVmGxP6akkZAoaiDhuyWnExa91HEQ8ZA3eZAUZCYafEpFeLRntT1ospyDdg7G4gBjjbCcGpZCJv2RUZD")
	    	pages = owner.accounts
		    page = pages.detect do |page|
		      page.identifier == "271138649706896"
		   	end
		   	page.feed!(
		    	:message => 'AirMeLive',
			  	:picture => cloud_url,
			  	:link => 'http://10.6.0.64:4567/upcomingevents/'+ id.to_s+'/show',
			  	:name => eventname,
			  	:description => description
				)
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	skip_before_action :require_login, except: [:post_upcoming_events]
	
=begin
	Action home provides details for the home page of the application.
	@up_events and @on_events are used to select the upcoming and 
	on going events respectively.	
=end

	def home
		if session[:user_id]
			@user = User.find session[:user_id]
		end
		@users = User.where('email != ?','airmelive@gmail.com').sort
		@date_today = DateTime.now.utc
		@up_events = Event.where('registrationopen <= ? and registrationclose > ?',@date_today,@date_today)
		@on_events = Event.where('eventopen <= ? and eventclose > ?',@date_today,@date_today)
	end

=begin
	upcoming_events action selects up coming events by comparing their date details
	with system date and store the events in @events.		
=end

	def upcoming_events
		if session[:user_id]
			@user = User.find session[:user_id]
		end
		@date_today = DateTime.now.utc
		@events = Event.where('registrationopen <= ? and registrationclose > ?',@date_today,@date_today)
	end

=begin
	ongoing_events action selects up coming events by comparing their date details
	with system date and store the events in @events.		
=end
	def ongoing_events
		if session[:user_id] 
			@user = User.find session[:user_id]
		end
		@date_today = DateTime.now.utc
		@events = Event.where('eventopen <= ? and eventclose > ?',@date_today,@date_today)
	end

=begin
	input : params[:id]
	for showing each upcoming event page.
=end	
	def show_up
		@event = Event.find(params[:id])
		@users = @event.users
		if session[:user_id]
			@user = User.find(session[:user_id])
		end
	end
=begin 
	Provide the option to participate in each upcoming event.
	Sends a confirmation mail to each user on participation.
=end
	def post_upcoming_events
		@user = User.find(session[:user_id])
		@event = Event.find(params[:id])
		check = UserEvent.where('user_id = ? and event_id = ?',session[:user_id], params[:id])
		
		if check.empty?
			user_event = UserEvent.create(user_id: session[:user_id],event_id: params[:id])				
			EventMailer.participation_email(@user,@event).deliver
			redirect_to upcoming_each_path(@event), :notice => "You have successfully registered"
		else
				flash[:notice] = 'You have already registered for this event'
		end
	end
end

app/helpers/events_helper.rb
module EventsHelper
	def round(no)

		if no%4 != 0
			no = (no+(4-(no%4)))/4 
		else
			no
		end

	end
end

app/views/events/home.html.erb
<div class = "container">

  <legend class="section"><a href="/upcomingevents"><h3 style="color:green">Upcoming Events</h3></a></legend>
<div class ="row">
  <% if @up_events.empty? %> 

    <h4 align="center"> No Upcoming Events!!! </h4>

  <% else %>
    <div class="col-md-12"> 
    <!-- Mango Flip List that triggers every 3 seconds -->
      <div class="list-tile mango">
          <ul class="flip-list fourTiles" data-mode="flip-list" data-delay="2000">
              <li>
                  <div><% if @up_events[0] %><a href="/upcomingevents/<%= @up_events[0].id%>/show"><%= image_tag @up_events[0].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @up_events[1] %><a href="/upcomingevents/<%= @up_events[1].id%>/show"><%= image_tag @up_events[1].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li>
                  <div><% if @up_events[2] %><a href="/upcomingevents/<%= @up_events[2].id%>/show"><%= image_tag @up_events[2].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @up_events[3] %><a href="/upcomingevents/<%= @up_events[3].id%>/show"><%= image_tag @up_events[3].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li>
                  <div><% if @up_events[4] %><a href="/upcomingevents/<%= @up_events[4].id%>/show"><%= image_tag @up_events[4].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @up_events[5] %><a href="/upcomingevents/<%= @up_events[5].id%>/show"><%= image_tag @up_events[5].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li data-direction="horizontal">
                  <div><% if @up_events[6] %><a href="/upcomingevents/<%= @up_events[6].id%>/show"><%= image_tag @up_events[6].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @up_events[7] %><a href="/upcomingevents/<%= @up_events[7].id%>/show"><%= image_tag @up_events[7].cloud_url %></a>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
          </ul>
      </div>
    </div>

    <% end %>
</div>
<legend class="section"><a href="/ongoingevents"><h3 style="color:green">Ongoing Events</h3></a></legend>
<div class ="row">
  <% if @on_events.empty? %> 

    <h4 align="center"> No Ongoing Events!!! </h4>

  <% else %>

     <div class="col-md-12"> 
    <!-- Mango Flip List that triggers every 3 seconds -->
      <div class="list-tile mango">
          <ul class="flip-list fourTiles" data-mode="flip-list" data-delay="2000">
              <li>
                  <div><% if @on_events[0] %><%= image_tag @on_events[0].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @on_events[1] %><%= image_tag @on_events[1].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li>
                  <div><% if @on_events[2] %><%= image_tag @on_events[2].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @on_events[3] %><%= image_tag @on_events[3].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li>
                  <div><% if @on_events[4] %><%= image_tag @on_events[4].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @on_events[5] %><%= image_tag @on_events[5].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
              <li data-direction="horizontal">
                  <div><% if @on_events[6] %><%= image_tag @on_events[6].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
                  <div><% if @on_events[7] %><%= image_tag @on_events[7].cloud_url %>
                  <% else %> <img src= "http://3.bp.blogspot.com/-dN2U6yN_xV0/UEYxkZyU_ZI/AAAAAAAACv8/ZESkFTJT4YU/s1600/Smiley+With+Tongue+Out.jpg"><% end %></div>
              </li>
          </ul>
      </div>
    </div>

  <% end %>
</div>

<legend class="section"><h3 style="color:green">Participants</h3></legend>
<div class="row">
  <% if @users.empty? %> 

    <h4 align="center"> No Participants!!! </h4>

  <% else %>

    <div id="participants" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" style="background-color:white;">
        
        <div class="item active">
          <div class="col-md-2"></div>
          <% for i in 0..3 %>
          <% if @users[i]%>
            <div class="col-md-2">
              <div class="thumbnail">
                <a href="/public_profile/<%= @users[i].id %>/"><%= image_tag @users[i].user_cloud_url ,:class => 'image_show' %></a>
                <div class="caption">
                  <p><%= @users[i].name %></p>
                </div>
              </div>
            </div>
            <%end%>
          <% end %>
        </div>
        <% k = 4 %>
        <% for i in 0...round(@users.count-4) %>
          <div class="item">
            <div class="col-md-2"></div>
            <% for j in k...k+4 %>
              <% if @users[j]%>
                <div class="col-md-2">
                  <div class="thumbnail">
                    <a href="/public_profile/<%= @users[j].id %>/"><%= image_tag @users[j].user_cloud_url ,:class => 'image_show' %></a>
                    <div class="caption">
                      <p><%= @users[j].name %></p>
                    </div>
                  </div>
                </div>
              <% end %>
              <% k = j+1 %>
            <% end %>
          </div>
        <% end %>
   
    </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#participants" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" style="color:green;"></span>
      </a>
      <a class="right carousel-control" href="#participants" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" style="color:green;"></span>
      </a>
    </div>

  <%end%>
</div>
<script type="text/javascript">
    // apply regular slide universally unless .exclude class is applied
    // NOTE: The default options for each liveTile are being pulled from the 'data-' attributes
    $(".live-tile, .flip-list").not(".exclude").liveTile();
</script>
</div>

 

app/views/events/ongoing_events.html.erb
<div class = "container">
	<% if @events.empty? %> 

  	<h1 align="center"> No Ongoing Events!!! </h1>

  <% else %>     
    <h3 style="color:green">On Going Events</h3>

    <div class="row">
      
    <% @events.each do |t| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= t.eventname.upcase %>
          <%= image_tag t.cloud_url ,:class => 'image_show' %>
          <div class="caption">
            <p><%= t.description %></p>
            <% if session[:user_id] %>
                <% unless @user.email == "airmelive@gmail.com" %>
                   <%= button_to "Vote", upcomingevents_path, class: "btn btn-success" %>
                <% end %>
            <% else %>
                <%= button_to "Vote", upcomingevents_path, class: "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    </div>
  <% end %>

</div>

app/views/events/post_upcoming_events.html.erb
<div class="span8 offset1">
	<section class="widget tiny">
		<div class="body">
				<p>You have already registered for this event</p>				
		</div>
	</section> 
</div>

app/views/events/show_up.html.erb
<div class="container">

<h4 align="center"><%= @event.eventname.upcase %></h4>
<div class="row">
		<%= image_tag @event.cloud_url ,:class => 'image_show_up' %>
</div>

<br><br>

<div class="row">  
	<div class="col-md-6">
			<legend class="section"><h4 style="color:green">DESCRIPTION</h4></legend>
			<p align="justify"><%= @event.description %></p>
      <% if @user %>
        <% unless @user.email == "airmelive@gmail.com"  %>
  			  <%= button_to "participate", upcoming_path(@event), class: "btn btn-success" %>
        <% end %>
      <% end %>
	</div>
  	<div class="col-md-6">
			<legend class="section"><h4 style="color:green">RULES</h4></legend>
			<p align="center"><%=@event.rules%></p>
	</div>
</div>

<br><br><br>

			<legend class="section"><h4 style="color:green">PARTICIPANTS</h4></legend>

<% if @users.empty? %> 

    <h4 align="center"> No Participants!!! </h4>

  <% else %>

    <div id="participants" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" style="background-color:white;">
        
        <div class="item active">
          <div class="col-md-2"></div>
          <% for i in 0..3 %>
            <div class="col-md-2">
            	<% if @users[i] %>
              	<div class="thumbnail">              	
                	<a href="/public_profile/<%= @users[i].id %>/"><%= image_tag @users[i].user_cloud_url ,:class => 'image_show' %></a>
                	<div class="caption">
                  	<p><%= @users[i].name %></p>
                	</div>
              	</div>
              <% end %>
            </div>
          <% end %>
        </div>
        <% k = 4 %>
        <% for i in 0...round(@users.count-4) %>
          <div class="item">
            <div class="col-md-2"></div>
            <% for j in k...k+4 %>
              <% if @users[j]%>
                <div class="col-md-2">
                  <div class="thumbnail">
                    <a href="/public_profile/<%= @users[j].id %>/"><%= image_tag @users[j].user_cloud_url ,:class => 'image_show' %></a>
                    <div class="caption">
                      <p><%= @users[j].name %></p>
                    </div>
                  </div>
                </div>
              <% end %>
              <% k = j+1 %>
            <% end %>
          </div>
        <% end %>
   
    </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#participants" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" style="color:green;"></span>
      </a>
      <a class="right carousel-control" href="#participants" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" style="color:green;"></span>
      </a>
    </div>

  <%end%>


</div>

app/views/events/upcoming_events.html.erb
<div class = "container">
  <% if @events.empty? %> 

  	<h1 align="center"> No Upcoming Events!!! </h1>

  <% else %> 

    <h3 style="color:green">Upcoming Events </h3>
    <div class="row">
      
    <% @events.each do |t| %>
      
      <div class="col-md-4">
        <div class="thumbnail">
          <p><%= link_to t.eventname.upcase , upcoming_each_path(t),:style => 'text-decoration: none'  %> </p>
          <%= image_tag t.cloud_url ,:class => 'image_show' %>
          <div class="caption">
            <p><%= t.description %></p>
            <% if session[:user_id] %>
                <% unless @user.email == "airmelive@gmail.com" %>
                    <%= button_to "participate", upcoming_path(t), class: "btn btn-success" %>
                <% end %>
            <% else %>
                <%= button_to "participate", upcoming_path(t), class: "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>

    <% end %>

  

    </div>
    <% end %>
</div>
<br><br><br>
<legend></legend>